# modules/document_writer.py

from pyrogram import Client, filters
from pyrogram.types import Message
from config import PREFIX
from datetime import datetime
import os

TEMP_DOC_DIR = "documents"
os.makedirs(TEMP_DOC_DIR, exist_ok=True)

@Client.on_message(filters.command("writedoc", prefixes=PREFIX) & filters.private)
async def write_doc_handler(client, message: Message):
    if len(message.command) < 2:
        return await message.reply("✍️ Please provide content to write in the document.\nExample: `/writedoc Hello world!`")

    content = message.text.split(None, 1)[1]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(TEMP_DOC_DIR, f"doc_{timestamp}.txt")

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    await message.reply_document(file_path, caption="📝 Here's your generated document.")
    os.remove(file_path)

@Client.on_message(filters.command("gendoc", prefixes=PREFIX) & filters.private)
async def generate_report(client, message: Message):
    text = "**📄 Sample Report Generated by Infinity AI Bot**\n\n"
    text += f"User: `{message.from_user.first_name}`\n"
    text += f"User ID: `{message.from_user.id}`\n"
    text += f"Date: `{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}`\n\n"
    text += "Sections:\n- Introduction\n- Stats Summary\n- Final Thoughts\n\n"
    text += "This document is auto-generated. Edit as needed."

    filename = f"{TEMP_DOC_DIR}/report_{message.from_user.id}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(text)

    await message.reply_document(filename, caption="📑 Auto-generated report.")
    os.remove(filename)